### ISSUE TITLE
Here link in ICPC section is not working

### ISSUE THREAD

**Issue by prabhxjottsingh** [kunal-kushwaha/Competitive-Programming-Resources#27]
*here* link in ICPC section is not working, it is redirecting the user to the following access denied page:
<p align = "center">
<img src = "https://user-images.githubusercontent.com/79351160/145399152-f3869ae6-dfce-427f-9207-5e568bb12f93.PNG" width = "700">
</p>
Can you assign me this issue, so that I can fix that link and as a solution the link would redirect the user to the following page:
<a href = "https://icpc.global/regionals/rules/"> here </a>

**Comment by prabhxjottsingh** [comment]
Hey, @kunal-kushwaha can you please look into this issue.
Thanks :)

**Comment by kunal-kushwaha** [comment]
make a PR
